MACOS_VER=10.15
cflags += -std=c99 -ftree-vectorize -mmacosx-version-min=$(MACOS_VER)

lib.name = z4th

z4th.class.sources := z4th.c zforth.c

datafiles = help-z4th.pd

include Makefile.pdlibbuilder


